### ISSUE TITLE
postgres

### ISSUE THREAD

**Issue by sid88in** [marianzange/knex-aws-xray#1]
Hey @marianzange does this plugin work for postgres?

**Comment by marianzange** [comment]
Since this module patches the event handlers on Knex instead of the db client, it should be agnostic to the underlying DB. However, please keep in mind that this package is a total prototype. I have neither tested it with Postgres nor am I actively developing this package at the moment. But feel free to give it a try and open PRs if you find any issues.

**Comment by sid88in** [comment]
sounds good! thanks
